name: Deploy Multi Docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t pdtg/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true pdtg/react-test npm test
      #build and tag
      - run: docker build -t pdtg/multi-client ./client
      - run: docker build -t pdtg/multi-nginx ./nginx
      - run: docker build -t pdtg/multi-server ./server
      - run: docker build -t pdtg/multi-worker ./worker
      #push to docker hub
      - run: docker push pdtg/multi-client
      - run: docker push pdtg/multi-nginx
      - run: docker push pdtg/multi-server
      - run: docker push pdtg/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react
      #     environment_name: Dockerreact-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-612498672922
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
